sudo: false
language: rust
matrix:
  include:
    - os: windows
      rust: stable

    - os: osx
      rust: stable

    - os: linux
      rust: stable
    - os: linux
      rust: beta
    - os: linux
      rust: nightly

env:
  - RUSTFLAGS="-Ctarget-feature=+aes,+ssse3" RUSTDOCFLAGS="-Ctarget-feature=+aes,+ssse3" RUST_BACKTRACE=1

addons:
  apt:
    packages:
      - libssl-dev

install:
  # Install OpenSSL on Windows
  - if [ "${TRAVIS_OS_NAME}" = "windows" ]; then
    curl -O "http://slproweb.com/download/Win64OpenSSL-1_1_0L.exe";
    cmd.exe /C 'Win64OpenSSL-1_1_0L.exe /SILENT /VERYSILENT /SP- /DIR="C:\OpenSSL"';
    export OPENSSL_LIB_DIR=/c/OpenSSL/lib;
    export OPENSSL_INCLUDE_DIR=/c/OpenSSL/include;
    export OPENSSL_DIR=/c/OpenSSL/bin;
    fi

  # Install libsodium on Windows
  - if [ "#{TRAVIS_OS_NAME}" = "windows" ]; then
    curl -O "https://download.libsodium.org/libsodium/releases/libsodium-1.0.18-stable-mingw.tar.gz";
    mkdir -p "/c/libsodium";
    tar -xf libsodium-1.0.18-stable-mingw.tar.gz -C "/c/libsodium";
    export SODIUM_INCLUDE_DIR=/c/libsodium/libsodium-win64/include;
    export SODIUM_LIB_DIR=/c/libsodium/libsodium-win64/lib;
    export SODIUM_STATIC=yes;
    else
    export SODIUM_BUILD_STATIC=yes;
    fi

script:
  - cargo test --no-fail-fast --features miscreant
