sudo: false
language: rust
jobs:
  include:
    - os: windows
      rust: stable

    - os: osx
      rust: stable

    - os: linux
      rust: stable
    - os: linux
      rust: beta
    - os: linux
      rust: nightly

  allow_failures:
    # FIXME: Travis build success but tests crash
    - os: windows
      rust: stable

env:
  - RUSTFLAGS="-Ctarget-feature=+aes,+ssse3" RUSTDOCFLAGS="-Ctarget-feature=+aes,+ssse3" RUST_BACKTRACE=1

addons:
  apt:
    packages:
      - libssl-dev

install:
  # Install OpenSSL on Windows
  - if [ "${TRAVIS_OS_NAME}" = "windows" ]; then
    curl -Lo "openssl-1.0.2c-win64-mingw.zip" "https://dl.bintray.com/vszakats/generic/openssl-1.0.2c-win64-mingw.zip";
    unzip "openssl-1.0.2c-win64-mingw.zip" -d "/c/OpenSSL";
    export OPENSSL_LIB_DIR=/c/OpenSSL/openssl-1.0.2c-win64-mingw;
    export OPENSSL_INCLUDE_DIR=/c/OpenSSL/openssl-1.0.2c-win64-mingw/include;
    export OPENSSL_DIR=/c/OpenSSL/openssl-1.0.2c-win64-mingw;
    fi

script:
  - cargo test --no-fail-fast
  - cargo test --no-fail-fast --features miscreant
  - cargo test --no-fail-fast --no-default-features
  - cargo test --no-fail-fast --features single-threaded
