[target.'cfg(any(target_arch = "x86", target_arch = "x86_64"))']
rustflags = [
    "-Ctarget-feature=+aes,+ssse3",
]

[target.'cfg(target_arch = "aarch64")']
rustflags = [
    "-Ctarget-feature=+aes,+crypto,+neon",
]
