name: Build Releases
on:
  push:
    tags:
      - v*

env:
  CARGO_TERM_COLOR: always

jobs:
  build-docker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install cross
        run: cargo install cross

      - name: Build x86_64-pc-windows-gnu
        timeout-minutes: 120
        run: |
          cd build
          docker build -t shadowsocks-rust:x86_64-pc-windows-gnu -f Dockerfile.x86_64-pc-windows-gnu .
          ./build-release -t shadowsocks-rust:x86_64-pc-windows-gnu

      - name: Build x86_64-unknown-linux-musl
        timeout-minutes: 120
        run: |
          cd build
          docker build -t shadowsocks-rust:x86_64-unknown-linux-musl -f Dockerfile.x86_64-unknown-linux-musl .
          ./build-release -t shadowsocks-rust:x86_64-unknown-linux-musl

      - name: Build x86_64-unknown-linux-gnu
        timeout-minutes: 120
        run: |
          cd build
          docker build -t shadowsocks-rust:x86_64-unknown-linux-gnu -f Dockerfile.x86_64-unknown-linux-gnu .
          ./build-release -t shadowsocks-rust:x86_64-unknown-linux-gnu

      - name: Build arm-unknown-linux-gnueabihf
        timeout-minutes: 120
        run: |
          cd build
          docker build -t shadowsocks-rust:arm-unknown-linux-gnueabihf -f Dockerfile.arm-unknown-linux-gnueabihf .
          ./build-release -t shadowsocks-rust:arm-unknown-linux-gnueabihf

      - name: Build aaarch64-unknown-linux-gnu
        timeout-minutes: 120
        run: |
          cd build
          docker build -t shadowsocks-rust:aaarch64-unknown-linux-gnu -f Dockerfile.aaarch64-unknown-linux-gnu .
          ./build-release -t shadowsocks-rust:aaarch64-unknown-linux-gnu

      - name: Build mips-unknown-linux-musl
        timeout-minutes: 120
        run: |
          cd build
          docker build -t shadowsocks-rust:mips-unknown-linux-musl -f Dockerfile.mips-unknown-linux-musl .
          ./build-release -t shadowsocks-rust:mips-unknown-linux-musl

      - name: Build mipsel-unknown-linux-musl
        timeout-minutes: 120
        run: |
          cd build
          docker build -t shadowsocks-rust:mipsel-unknown-linux-musl -f Dockerfile.mipsel-unknown-linux-musl .
          ./build-release -t shadowsocks-rust:mipsel-unknown-linux-musl

      - uses: actions/upload-artifact@v2
        with:
          name: releases
          path: build/release/*

  build-unix:
    runs-on: ${{ matrix.os }}
    env:
      BUILD_EXTRA_FEATURES: "openssl-vendored local-redir"
      RUSTFLAGS: "-Ctarget-feature=+aes,+ssse3"
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
    steps:
      - uses: actions/checkout@v2
      - name: Build release
        shell: bash
        run: |
          cd build
          ./build-host-release
      - uses: actions/upload-artifact@v2
        with:
          name: releases
          path: build/release/*

  build-windows:
    runs-on: windows-latest
    env:
      OPENSSL_STATIC: 1
      OPENSSL_DIR: "C:\\Program Files\\OpenSSL-Win64\\"
      RUSTFLAGS: "-Ctarget-feature=+aes,+ssse3"
    steps:
      - uses: actions/checkout@v2
      - name: Build release
        run: |
          cd build
          pwsh build-host-release.ps1
      - uses: actions/upload-artifact@v2
        with:
          name: releases
          path: build/release/*
