name: Build & Test

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

env:
  CARGO_TERM_COLOR: always
  RUSTFLAGS: "-Ctarget-feature=+aes,+ssse3"
  RUST_LOG: "shadowsocks=trace"

jobs:
  build-linux:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v2
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
      - name: Install Rust nightly
        run: rustup toolchain install nightly
      - name: Build & Test (Default)
        run: cargo +nightly test --verbose --no-fail-fast
      - name: Build & Test (--no-default-feature)
        run: cargo +nightly test --verbose --no-default-feature --no-fail-fast
      - name: Build with All Features Enabled
        run: cargo +nightly build --verbose --features "local-redir local-dns local-http-rustls dns-over-tls dns-over-https"

  build-windows:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v2
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
      - name: Install Rust nightly
        run: rustup toolchain install nightly
      - name: Build & Test (Default)
        run: cargo +nightly test --verbose --no-fail-fast
      - name: Build & Test (--no-default-feature)
        run: cargo +nightly test --verbose --no-default-feature --no-fail-fast
      - name: Build with All Features Enabled
        run: cargo +nightly build --verbose --features "local-dns local-http-rustls dns-over-tls dns-over-https"

  build-macos:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v2
      - name: Install GNU tar
        run: |
          brew install gnu-tar
          # echo "::add-path::/usr/local/opt/gnu-tar/libexec/gnubin"
          echo "/usr/local/opt/gnu-tar/libexec/gnubin" >> $GITHUB_PATH
      - uses: actions/cache@v2
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
      - name: Install Rust nightly
        run: rustup toolchain install nightly
      - name: Build & Test (Default)
        run: cargo +nightly test --verbose --no-fail-fast
      - name: Build & Test (--no-default-feature)
        run: cargo +nightly test --verbose --no-default-feature --no-fail-fast
      - name: Build with All Features Enabled
        run: cargo +nightly build --verbose --features "local-redir local-dns local-http-rustls dns-over-tls dns-over-https"
